title: VAIRA Technology
url: "https://vaira.ch"
baseurl: ""
theme: null
markdown: kramdown

# Required for github-pages gem (jekyll-github-metadata)
repository: raphaelheeb/vaira-advisory

# ----------------------------------------
# Collections
# ----------------------------------------
collections:
  insights:
    output: true
    permalink: /insights/:name/
  de_insights:
    output: true
    permalink: /de/insights/:name/

