title: VAIRA Technology
url: "https://vaira.ch"
baseurl: ""
theme: null
markdown: kramdown

# Required for github-pages gem (jekyll-github-metadata)
repository: raphaelheeb/vaira-advisory

# ----------------------------------------
# Collections
# ----------------------------------------
collections:
  insights:
    output: true
    permalink: /insights/:name/
  de_insights:
    output: true
    permalink: /de/insights/:name/

theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-include-cache

# Force GitHub Pages to NOT load Minima
github:
  theme: null

