title: VAIRA Technology
url: "https://vaira.ch"
baseurl: ""
theme: null
markdown: kramdown

# GitHub Pages does NOT allow custom plugins like jekyll-sitemap.
# We will provide our own sitemap.xml manually.
exclude:
  - sitemap.xml
